### ISSUE TITLE
[AD] Remaining scorpio tasks

### ISSUE THREAD

**Issue by AaronDonahue** [E3SM-Project/scream#880]
This issue makes it easier to understand what the remaining tasks for the scorpio interface are by combining them all together:

**High Priority**
- [x] Assure that I/O can handle variables that are packed - see #787 

**Medium Priority**
- [x] Get restarts working as expected - see #798 
- [x] Investigate the output file naming convention - see #789 
- [ ] YAML control of netCDF header - see #788 
- [ ] Automatic registration of dimensions as variables - see #786 
- [ ] Enable PIO_STRIDE - see #785 
- [x] Allow compile time adjustment of individual output control files during a CIME build - see #879
- [x] Add treatment for DIM field tag in I/O - see #930 
- [x] Switch input class to using grid rather than grid manager at construction - see #1109 

**Low Priority**
- [x] Make input able to handle files with more than one timesnap - see #799 
- [x] Make restart a separate sub-class of output class - see #797 
- [x] Better handling of output frequency - see #790 

**Wishlist**
- [x] Get rid of remaining F90 code in SCREAMv1 I/O interface - see #823 and #792 
- [x] Make an "averaging type" class for future flexibility - see #795 
- [ ] Create an I/O class that has output and input as sub-classes - see #794 
- [ ] Add option to write a restart at finalization regardless of restart frequency - see #793 
- [x] Allow for output on dynamics grid - see #791 
- [ ] Make it possible for SCREAM to output initial condition files.
- [ ] Allow SCREAM to load true non-hydrostatic IC files **and** hydrostatic IC files.
